{"name": "注册账号", "status": "broken", "statusDetails": {"message": "pymysql.err.ProgrammingError: (1064, \"You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'LIMITI 1' at line 1\")", "trace": "self = <testcases.test_user.TestUser object at 0x000001B030F04430>\ndriver = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"e6289fc51ac00af5cf0bf815877157ce\")>\n\n    @allure.title('注册账号')\n    def test_register(self, driver):\n        page = UserPage(driver)\n        data = read_yaml()['register_ok']\n        with allure.step('Click register botton'):\n            page.click(page.btn_register)\n    \n        with allure.step('Input username'):\n            page.send_keys(page.input_phone, data['mobile'])\n    \n        with allure.step('Fetch authentication code'):\n            page.click(page.btn_code)\n    \n        with allure.step('获取验证码'):\n            sql = f\"SELECT code FROM users_verifycode WHERE mobile ={str(data['mobile'])} ORDER BY id LIMITI 1\"\n>           code = db.select_db_one(sql)['code']\n\ntest_user.py:66: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n..\\utils\\mysql_util.py:25: in select_db_one\n    self.cur.execute(query=sql)\n..\\venv\\lib\\site-packages\\pymysql\\cursors.py:153: in execute\n    result = self._query(query)\n..\\venv\\lib\\site-packages\\pymysql\\cursors.py:322: in _query\n    conn.query(q)\n..\\venv\\lib\\site-packages\\pymysql\\connections.py:558: in query\n    self._affected_rows = self._read_query_result(unbuffered=unbuffered)\n..\\venv\\lib\\site-packages\\pymysql\\connections.py:822: in _read_query_result\n    result.read()\n..\\venv\\lib\\site-packages\\pymysql\\connections.py:1200: in read\n    first_packet = self.connection._read_packet()\n..\\venv\\lib\\site-packages\\pymysql\\connections.py:772: in _read_packet\n    packet.raise_for_error()\n..\\venv\\lib\\site-packages\\pymysql\\protocol.py:221: in raise_for_error\n    err.raise_mysql_exception(self._data)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\ndata = b\"\\xff(\\x04#42000You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'LIMITI 1' at line 1\"\n\n    def raise_mysql_exception(data):\n        errno = struct.unpack(\"<h\", data[1:3])[0]\n        errval = data[9:].decode(\"utf-8\", \"replace\")\n        errorclass = error_map.get(errno)\n        if errorclass is None:\n            errorclass = InternalError if errno < 1000 else OperationalError\n>       raise errorclass(errno, errval)\nE       pymysql.err.ProgrammingError: (1064, \"You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'LIMITI 1' at line 1\")\n\n..\\venv\\lib\\site-packages\\pymysql\\err.py:143: ProgrammingError"}, "steps": [{"name": "Click register botton", "status": "passed", "start": 1691914026840, "stop": 1691914026912}, {"name": "Input username", "status": "passed", "start": 1691914026912, "stop": 1691914027010}, {"name": "Fetch authentication code", "status": "passed", "start": 1691914027010, "stop": 1691914027058}, {"name": "获取验证码", "status": "broken", "statusDetails": {"message": "pymysql.err.ProgrammingError: (1064, \"You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'LIMITI 1' at line 1\")\n", "trace": "  File \"D:\\Career\\Practice\\Project\\testcases\\test_user.py\", line 66, in test_register\n    code = db.select_db_one(sql)['code']\n  File \"D:\\Career\\Practice\\Project\\utils\\mysql_util.py\", line 25, in select_db_one\n    self.cur.execute(query=sql)\n  File \"D:\\Career\\Practice\\Project\\venv\\lib\\site-packages\\pymysql\\cursors.py\", line 153, in execute\n    result = self._query(query)\n  File \"D:\\Career\\Practice\\Project\\venv\\lib\\site-packages\\pymysql\\cursors.py\", line 322, in _query\n    conn.query(q)\n  File \"D:\\Career\\Practice\\Project\\venv\\lib\\site-packages\\pymysql\\connections.py\", line 558, in query\n    self._affected_rows = self._read_query_result(unbuffered=unbuffered)\n  File \"D:\\Career\\Practice\\Project\\venv\\lib\\site-packages\\pymysql\\connections.py\", line 822, in _read_query_result\n    result.read()\n  File \"D:\\Career\\Practice\\Project\\venv\\lib\\site-packages\\pymysql\\connections.py\", line 1200, in read\n    first_packet = self.connection._read_packet()\n  File \"D:\\Career\\Practice\\Project\\venv\\lib\\site-packages\\pymysql\\connections.py\", line 772, in _read_packet\n    packet.raise_for_error()\n  File \"D:\\Career\\Practice\\Project\\venv\\lib\\site-packages\\pymysql\\protocol.py\", line 221, in raise_for_error\n    err.raise_mysql_exception(self._data)\n  File \"D:\\Career\\Practice\\Project\\venv\\lib\\site-packages\\pymysql\\err.py\", line 143, in raise_mysql_exception\n    raise errorclass(errno, errval)\n"}, "start": 1691914027058, "stop": 1691914027107}], "attachments": [{"name": "log", "source": "98c7a24f-3a89-4146-95ed-ecbb80506811-attachment.txt", "type": "text/plain"}], "start": 1691914026840, "stop": 1691914027115, "uuid": "39b7dd6a-4825-4f0e-8a78-b4a11f6690ab", "historyId": "1b7d7a66b0ca91af2c9d05421dccae81", "testCaseId": "1b7d7a66b0ca91af2c9d05421dccae81", "fullName": "testcases.test_user.TestUser#test_register", "labels": [{"name": "feature", "value": "Module: User"}, {"name": "epic", "value": "Project: Meike Market"}, {"name": "parentSuite", "value": "testcases"}, {"name": "suite", "value": "test_user"}, {"name": "subSuite", "value": "TestUser"}, {"name": "host", "value": "Ted"}, {"name": "thread", "value": "10884-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcases.test_user"}]}